#? this is an example of `/etc/ocis/ocis.yaml`
token_manager:
  jwt_secret: jwy$KmL*dmf385dMc!TalanKy$WKehn=
machine_auth_api_key: 06fq6%e!^37F!-=$JBYUzuBF+r$2jHA^
system_user_api_key: P$k+51@tzjDmZ.pmB0eamAHr58mwOb%V
transfer_secret: TyoZ4I%XddPb7T0SS4g-7b*a9MJ7XR0y
system_user_id: ffad4357-80b2-4054-bb84-41715d042aa5
admin_user_id: 1fe8842b-bc2a-423e-8d27-5cda3c19f367
graph:
  application:
    id: 75797d3f-b737-41d4-b1f2-1a1078b0340b
  events:
    tls_insecure: false
  spaces:
    insecure: false
  identity:
    ldap:
      bind_password: BxETr-oBO@G2wQaG@.MS@Ou=lg*8AZp&
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
idp:
  ldap:
    bind_password: Vb8c9gFWQpXaaMu9rWrCTw$7zLa%*zy8
idm:
  service_user_passwords:
    admin_password: changeme
    idm_password: BxETr-oBO@G2wQaG@.MS@Ou=lg*8AZp&
    reva_password: DFx.JC@AfxFWc=@a!kLwCtdPDi.GEm6G
    idp_password: Vb8c9gFWQpXaaMu9rWrCTw$7zLa%*zy8
proxy:
  oidc:
    insecure: false
  insecure_backends: false
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
frontend:
  app_handler:
    insecure: false
  archiver:
    insecure: false
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
auth_basic:
  auth_providers:
    ldap:
      bind_password: DFx.JC@AfxFWc=@a!kLwCtdPDi.GEm6G
auth_bearer:
  auth_providers:
    oidc:
      insecure: false
users:
  drivers:
    ldap:
      bind_password: DFx.JC@AfxFWc=@a!kLwCtdPDi.GEm6G
groups:
  drivers:
    ldap:
      bind_password: DFx.JC@AfxFWc=@a!kLwCtdPDi.GEm6G
ocdav:
  insecure: false
ocm:
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
thumbnails:
  thumbnail:
    transfer_secret: pFs#mc&9fbL4&Z4^-UMH%c9L+ZLbzn.N
    webdav_allow_insecure: false
    cs3_allow_insecure: false
search:
  events:
    tls_insecure: false
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
audit:
  events:
    tls_insecure: false
settings:
  service_account_ids:
    - 85f32081-a266-425b-bb43-140eb33d5eea
sharing:
  events:
    tls_insecure: false
storage_users:
  events:
    tls_insecure: false
  mount_id: 735e0289-57de-4d97-9a72-f7e104dd7a3f
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
notifications:
  notifications:
    events:
      tls_insecure: false
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
nats:
  nats:
    tls_skip_verify_client_cert: false
gateway:
  storage_registry:
    storage_users_mount_id: 735e0289-57de-4d97-9a72-f7e104dd7a3f
userlog:
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
auth_service:
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
clientlog:
  service_account:
    service_account_id: 85f32081-a266-425b-bb43-140eb33d5eea
    service_account_secret: 0Q$W%J%V%RzN@AyYr!4Uy49o8D&ZT^^G
