#? sudo cat /root/snap/owncloud-infinite/current/etc/ocis/ocis.yaml
token_manager:
  jwt_secret: hH+#KDX!H*cG-vg8N&T@KS1m$A4!y7mi
machine_auth_api_key: rdZDzOpdYprFb**^$P=hWj.m!FQLzasi
system_user_api_key: 2.TGN5JmwW@d$Hno5!eXuS3sxs#vacGm
transfer_secret: nQmL8j18kwgf!qHS4X+h2fijDsdAiFEn
system_user_id: edbd50f5-47c9-44c7-9361-34f41310bcb2
admin_user_id: 11a87c77-0da4-4020-8bd1-be7c0683dc20
graph:
  application:
    id: c68189fc-3929-4844-af56-36b143b5d605
  events:
    tls_insecure: true
  spaces:
    insecure: true
  identity:
    ldap:
      bind_password: -$SgMO=B#qtLmat3ra72Sk1^.eze5yTK
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
idp:
  ldap:
    bind_password: RaZNpY.yNs*-1A-$ESkQph==z8fNjMV&
idm:
  service_user_passwords:
    admin_password: changeme
    idm_password: -$SgMO=B#qtLmat3ra72Sk1^.eze5yTK
    reva_password: uK2ZRLgf^Xyrx1MPXcFy7d9qSYcrJCsk
    idp_password: RaZNpY.yNs*-1A-$ESkQph==z8fNjMV&
proxy:
  oidc:
    insecure: true
  insecure_backends: true
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
frontend:
  app_handler:
    insecure: true
  archiver:
    insecure: true
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
auth_basic:
  auth_providers:
    ldap:
      bind_password: uK2ZRLgf^Xyrx1MPXcFy7d9qSYcrJCsk
auth_bearer:
  auth_providers:
    oidc:
      insecure: true
users:
  drivers:
    ldap:
      bind_password: uK2ZRLgf^Xyrx1MPXcFy7d9qSYcrJCsk
groups:
  drivers:
    ldap:
      bind_password: uK2ZRLgf^Xyrx1MPXcFy7d9qSYcrJCsk
ocdav:
  insecure: true
ocm:
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
thumbnails:
  thumbnail:
    transfer_secret: -ZG*UL%kU8nkodx^qTkS+i0@GA&Ua3AD
    webdav_allow_insecure: true
    cs3_allow_insecure: true
search:
  events:
    tls_insecure: true
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
audit:
  events:
    tls_insecure: true
settings:
  service_account_ids:
    - 23953689-2968-484e-93e0-2e5327f163f2
sharing:
  events:
    tls_insecure: true
storage_users:
  events:
    tls_insecure: true
  mount_id: 4d465115-dde4-4648-a964-a1dfc41b9bf7
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
notifications:
  notifications:
    events:
      tls_insecure: true
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
nats:
  nats:
    tls_skip_verify_client_cert: true
gateway:
  storage_registry:
    storage_users_mount_id: 4d465115-dde4-4648-a964-a1dfc41b9bf7
userlog:
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
auth_service:
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
clientlog:
  service_account:
    service_account_id: 23953689-2968-484e-93e0-2e5327f163f2
    service_account_secret: GM!b0aH$3J7sV%24=uU86Nb2UDduZhd0
