## Static configuration
# # define entrypoints
# - "--entryPoints.http.address=:80"
# - "--entryPoints.http.http.redirections.entryPoint.to=https"
# - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
# - "--entryPoints.https.address=:443"
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"
# - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
log:
  level: "${TRAEFIK_LOG_LEVEL:-ERROR}"
# # access log
# - "--accessLog=true"
# - "--accessLog.format=json"
# - "--accessLog.fields.headers.names.X-Request-Id=keep"
accessLog:
  format: json
  fields:
    headers:
      names:
        X-Request-Id: keep
# # letsencrypt configuration
# - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
# - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
# - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
# certificatesResolvers:
#   http:
#     acme:
#       storage: "${SNAP_COMMON}/certs/acme.json"
#       httpChallenge:
#         entryPoint: http
#       # email:
#? enable dashboard
# - "--api.dashboard=true"
api:
  dashboard: true
providers:
  # Enable the file provider to define routers / middlewares / services in file
  providers:
  file:
    directory: $SNAP_COMMON/etc/traefik/providers
    watch: true
  # file:
  #   directory: /etc/traefik/providers/project-name.yaml
