## Static configuration
# # define entrypoints
# - "--entryPoints.http.address=:80"
# - "--entryPoints.http.http.redirections.entryPoint.to=https"
# - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
# - "--entryPoints.https.address=:443"
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"
# - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
log:
  level: "${TRAEFIK_LOG_LEVEL:-ERROR}"

#? enable dashboard
# - "--api.dashboard=true"
api:
  dashboard: true

# # letsencrypt configuration
# - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
# - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
# - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: ${SNAP_COMMON}/etc/traefik/certs/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http

# - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
# - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
# - "traefik.http.routers.traefik.entrypoints=https"
# - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.owncloud.test}`)"
# - "traefik.http.routers.traefik.middlewares=traefik-auth"
# - "traefik.http.routers.traefik.tls.certresolver=http"
# - "traefik.http.routers.traefik.service=api@internal"
providers:
  # Enable the file provider to define routers / middlewares / services in file
  providers:
  file:
    directory: $SNAP_COMMON/etc/traefik/providers
    watch: true
  # file:
  #   directory: /etc/traefik/providers/project-name.yaml
