# GLOBAL METADATA
## Reference: https://snapcraft.io/docs/snapcraft-yaml-reference
## The name must be unique in the Snap Store.
## Valid snap names consist of lower-case alphanumeric characters and hyphens.
## They cannot be all numbers and they also cannot start or end with a hyphen.
name: owncloud-infinite # you probably want to 'snapcraft register <name>'
## The <base> keyword defines a special kind of snap that provides a run-time environment
## with a minimal set of libraries that are common to most applications.
## They’re transparent to users, but they need to be considered, and specified, when building a snap.
base: core22 # the base snap is the execution environment for this snap
version: "5.0.5+git" # just for humans, typically '1.2+git' or '1.3.2'
summary: ownCloud infinite scale # 79 char long summary
description: |
  To create a truly federated storage architecture oCIS breaks down the old ownCloud 10 user specific namespace, 
  which is assembled on the server side, and makes the individual parts accessible to clients as storage spaces 
  and storage space registries.
website: https://owncloud.dev/ocis/
# icon: <icon path?>
license: MIT

# ARCHITECTURES
## builds a snap to run on the same architecture as the build environment.
## ref: https://snapcraft.io/docs/architectures
# architectures:
#- build-on: arm64
#    build-for:
# - build-on: arm64
# build-for: arm64
# - build-on: amd64

lint:
  ignore:
    - library
# SECURITY MODEL
## Because devmode is only intended for development,
## snaps must be set to strict confinement before they can be published as “stable” in the Snap Store.
## Once an app is working well in devmode, you can review confinement violations,
## add appropriate interfaces, and switch to strict confinement.
confinement: devmode # use 'strict' once you have the right plugs and slots
## Defines the quality grade of the snap.
## Can be either devel (i.e. a development version of the snap,
## so not to be published to the stable or candidate channels) or
## stable (i.e. a stable release or release candidate, which can be released to all channels).
## A snap of type app (default) cannot be set to stable if the base is not on a stable channel.
grade: devel # must be 'stable' to release into candidate/stable channels

# PARTS
## are the raw building blocks of a snap, used to collect and build binaries and their dependencies.
## Parts define what sources are needed to assemble your app.
## Parts can be anything: programs, libraries, or other needed assets.
parts:
  ## The parts arbitrary name
  # node:
  #   plugin: npm
  #   source: .
  #   npm-include-node: true
  #   npm-node-version: 20

  # common:
  #   plugin: dump
  #   source: src/common/

  hooks:
    plugin: dump
    source: src/hooks/
    organize:
      bin/: snap/hooks/

  ocis:
    plugin: dump
    # https://download.owncloud.com/ocis/ocis/stable/5.0.5/ocis-5.0.5-linux-arm64
    source: src/ocis/
    organize:
      bin/: usr/bin/
    # "ocis*": /usr/bin/ocis
    stage:
      - usr/bin/*

    build-environment:
      - OCIS_CONFIG_DIR: $CRAFT_STAGE/etc/ocis/
      - OCIS_BASE_DATA_PATH: $CRAFT_STAGE/var/lib/ocis
      # TODO: for end user to change
      - IDM_ADMIN_PASSWORD: changeme
    override-build: |
      craftctl default
      echo "$OCIS_CONFIG_DIR" "$OCIS_BASE_DATA_PATH"

    stage-snaps:
      #? used to manage ocis configuration
      - yq

    override-stage: |
      craftctl default
      mkdir -p $OCIS_CONFIG_DIR
      mkdir -p $OCIS_BASE_DATA_PATH
      ls -al .
      chmod +x "$CRAFT_STAGE/usr/bin/ocis"
      # ls -al .
      ocis init

    override-prime: |
      craftctl default
      # mkdir -p $CRAFT_PRIME/{etc,var}
      cp -r $CRAFT_STAGE/etc $CRAFT_PRIME
      cp -r $CRAFT_STAGE/var $CRAFT_PRIME
      ls -al .
      cat $CRAFT_PRIME/etc/ocis/ocis.yaml

  # override-build: |
  #   curl -sSL \ "https://github.com/bufbuild/buf/releases/download/${BUF_VERSION}/buf-$(shell uname -s)-$(shell uname -m)" -o "$(shell go env GOPATH)/bin/buf" && chmod +x "$(shell go env GOPATH)/bin/buf"
  # ocis:
  #   ## The plugin field=(dump) determines how the information in specified in the source field
  #   ## and includes the source's contents in the snap.
  #   ## The source can be a local or remote zip file, deb file, or tarball.

  #   # plugin: make
  #   # plugin: npm
  #   # npm-node-version: 22
  #   # npm-include-node: true

  #   plugin: go
  #   ## (list of strings) Features used to build optional dependencies
  #   build-snaps:
  #     - go
  #   source-type: git
  #   source-tag: v5.0.5
  #   source: https://github.com/owncloud/ocis.git
  #   ## Before building the part, the packages listed in the build-packages section
  #   ## need to be installed in the build environment.
  #   ## These are the tools and libraries that are used during the build process.
  #   build-packages:
  #     - make
  #     - curl
  #     - wget
  #     - npm
  #   build-environment:
  #     - OCIS_CONFIG_DIR: $SNAP_USER_COMMON
  #     - OCIS_BASE_DATA_PATH: $SNAP_DATA
  #   # stage-packages:
  #   #   - pulseaudio
  #   #   - libfdk-aac-dev
  #   ## These are packages containing libraries are resources that the final snap needs to run.
  #   ## They are very similar to those that would be listed as run-time
  #   ## dependencies on a standard distribution package.
  #   #stage-packages:
  #   ## You can override and customise steps of a part’s lifecycle (pull, build, stage, and prime) using overrides;
  #   ## ref: https://snapcraft.io/docs/overrides
  #   override-build: |
  #     # Clean NPM cache
  #     # npm cache clean -f

  #     # Update NPM globally
  #     npm update -g npm
  #     npm --version

  #     # Install N globally
  #     npm install -g n

  #     # Prune older versions & Install latest node version
  #     n prune && n lts
  #     node --version
  #     hash -r

  #     ## install pnpm globally
  #     npm install -g @pnpm/exe
  #     ## npm install -g pnpm

  #     ## You only need to run following command if you have changed protobuf definitions
  #     ## or the frontend part in one of the extensions. Run the command in the root directory of the repository.
  #     ## Otherwise you can skip this step and proceed to build the oCIS binary.
  #     ## This will usually modify multiple embed.go files because we embed the frontend build output in these embed.go
  #     ## files and a timestamp will be updated and also minor differences are expected between different Node.js versions.
  #     # make generate

  #     ## build the binary
  #     make -C ocis build

  #     echo $CRAFT_PART_INSTALL

  #     ls -al

  #   # * Default staging will `cp` from `build` '/data/parts/ocis/build/ocis/bin/` to `/data/parts/ocis/stage/`
  #   # * yielding e.g.
  #   # * ```shell
  #   # * ls -al /data/parts/ocis/stage
  #   # * total Xxx
  #   # * drwxr-xr-x 2 root root 4096 May 31 00:06 ..
  #   # * # [...]
  #   # * drwxr-xr-x 2 root root 4096 May 31 00:06 bin
  #   # * ```
  #   override-stage: |
  #     # snapcraftctl stage

  #     if [ -e "$CRAFT_PART_INSTALL/bin/ocis" ]; then
  #       echo "File exists, copying"
  #       cp -r $CRAFT_PART_INSTALL/bin/ $CRAFT_PART_STAGE/bin
  #     else
  #         echo "File does not exist in $CRAFT_PART_INSTALL"
  #         ls -al "$CRAFT_PART_INSTALL/bin"
  #         ls -al "$CRAFT_PART_STAGE"
  #         echo "Checking build folder $CRAFT_PART_BUILD"
  #       if [ -e "$CRAFT_PART_BUILD/ocis/bin/ocis" ]; then
  #         echo "File exists in $CRAFT_PART_BUILD/ocis/bin/ocis"
  #         cp -r $CRAFT_PART_BUILD/ocis/bin/ $CRAFT_PART_STAGE/bin
  #       else
  #         echo "File does not exist in $CRAFT_PART_BUILD"
  #         ls -al "$CRAFT_PART_BUILD/ocis/bin"
  #         ls -al "$CRAFT_PART_STAGE"
  #       fi
  #     fi

  #   override-prime: |
  #     snapcraftctl prime
  #     ls -al ./bin
  #     # ./bin/ocis init

# APPS
## ref: https://snapcraft.io/docs/snapcraft-app-and-service-metadata
apps:
  ## ref: https://snapcraft.io/docs/services-and-daemons
  # some-daemon:
  #   command: bin/os-release.sh
  #   daemon: simple
  ocis:
    # adapter: full
    # WORKAROUND: Snapcraft impose too much restrictions to the command format
    # https://bugs.launchpad.net/snapcraft/+bug/1820055
    # initialize a minimal oCIS configuration
    #  ./ocis/bin/ocis init
    install-mode: disable
    command: /usr/bin/ocis server
    daemon: simple
    environment:
      #* run with demo users
      # IDM_CREATE_DEMO_USERS: true

      #? https://doc.owncloud.com/ocis/next/deployment/general/general-info.html#default-paths
      #* Path to config files.
      #* The configuration directory has a default location for config files, which must be on a POSIX storage:
      #*  - For container images (inside the container) => `/etc/ocis/`
      #*  - For binary releases => `$HOME/.ocis/config/`
      # Directory for user data that is common across revisions of a snap.
      # Unlike SNAP_USER_DATA, data present in this directory is not backed up or restored across snap refresh
      # and snap revert operations. The directory is suitable for large data that the application can access even
      # if it was made or modified by a future version of a snap.
      # ==> $HOME/snap/$SNAP_NAME/common
      OCIS_CONFIG_DIR: $SNAP_USER_COMMON

      #* Path to system relevant data.
      #* Because Infinite Scale does not use a database for storing information like users, groups, spaces, internal data, etc.,
      #* it saves all this data to a permanent file location. Depending on the system setup, the base directory contains not
      #* only the metadata but also blobs. See Filesystems and Shared Storage for more details.
      #* The base path has a default location for metadata and service dependent data (see above) which must be on a POSIX storage.
      #* If not otherwise defined when using S3, it is also used to store blobs using that path:
      #*   - For container images (inside the container) => `/var/lib/ocis`
      #*   - For binary releases => `$HOME/.ocis/`

      #* `SNAP_DATA`
      #* Directory for system data of a snap. This directory is owned and writable by root and is meant to be used by background applications
      #* (daemons, services). Unlike `SNAP_COMMON` this directory is backed up and restored across snap refresh and snap revert operations.
      # ==> /var/snap/$SNAP_NAME/$SNAP_REVISION

      OCIS_BASE_DATA_PATH: $SNAP_DATA

      #* Path to blobs and metadata if POSIX is used.
      #* Derives from `OCIS_BASE_DATA_PATH` if not set otherwise.
      #* Used if `STORAGE_USERS_DRIVER` is set to ocis
      # STORAGE_USERS_OCIS_ROOT: xx

      #* Path to metadata if S3 is used.
      #* Derives from OCIS_BASE_DATA_PATH if not set otherwise.
      #* Used if STORAGE_USERS_DRIVER is set to s3ng.
      #* See Using S3 for Blobs for the S3 configuration.
      #*   When using S3 for storing user data (blobs), metadata must reside on POSIX. The environment variable responsible for
      #*   storaing metadata in S3 is `STORAGE_USERS_S3NG_ROOT` and derives, if not otherwise defined, from the base directory
      #*   `OCIS_BASE_DATA_PATH`. For more details see the section Base Data Directory above.
      # STORAGE_USERS_S3NG_ROOT: xx
      # GOPLAY2_CONFIG_PATH: /$SNAP_USER_DATA/.config
    plugs:
      ## Network Access
      - network
      - network-bind
      ## Removeable Devices
      ##? removable-media allows read/write access to mounted removable storage in `/media`, `/run/media` and `/mnt`.
      - removable-media
